### ISSUE TITLE
Informations

### ISSUE THREAD

**Issue by coolpalani** [starhawking/ansible-role-fuel-devops#1]
Hello,

May I know scope of your playbooks?
I am currently truing to build a Mirantis OpenStack 9.0, can i use your playbooks to do?
if so, could you provide playbook commands that need to setup?

**Comment by starhawking** [comment]
This playbook isn't for deploying Fuel. It deploys fuel-devops, a tool for preparing a test environment for deploying fuel.

This playbook deploys  https://github.com/openstack/fuel-devops/
